import assert from "node:assert/strict";
import { test } from "node:test";
import { step1 } from "../src/many/step1.ts";
import { step2 } from "../src/many/step2.ts";
import { step3 } from "../src/many/step3.ts";
import { step4 } from "../src/many/step4.ts";
import { step5 } from "../src/many/step5.ts";
import { step6 } from "../src/many/step6.ts";
import { step7 } from "../src/many/step7.ts";
import { step8 } from "../src/many/step8.ts";
import { step9 } from "../src/many/step9.ts";
import { step10 } from "../src/many/step10.ts";
import { step11 } from "../src/many/step11.ts";
import { step12 } from "../src/many/step12.ts";
import { step13 } from "../src/many/step13.ts";
import { step14 } from "../src/many/step14.ts";
import { step15 } from "../src/many/step15.ts";
import { step16 } from "../src/many/step16.ts";
import { step17 } from "../src/many/step17.ts";
import { step18 } from "../src/many/step18.ts";
import { step19 } from "../src/many/step19.ts";
import { step20 } from "../src/many/step20.ts";
import { step21 } from "../src/many/step21.ts";
import { step22 } from "../src/many/step22.ts";
import { step23 } from "../src/many/step23.ts";
import { step24 } from "../src/many/step24.ts";
import { step25 } from "../src/many/step25.ts";

test("every step adds its number", () => {
  assert.equal(step1(0), 1);
  assert.equal(step2(0), 2);
  assert.equal(step3(0), 3);
  assert.equal(step4(0), 4);
  assert.equal(step5(0), 5);
  assert.equal(step6(0), 6);
  assert.equal(step7(0), 7);
  assert.equal(step8(0), 8);
  assert.equal(step9(0), 9);
  assert.equal(step10(0), 10);
  assert.equal(step11(0), 11);
  assert.equal(step12(0), 12);
  assert.equal(step13(0), 13);
  assert.equal(step14(0), 14);
  assert.equal(step15(0), 15);
  assert.equal(step16(0), 16);
  assert.equal(step17(0), 17);
  assert.equal(step18(0), 18);
  assert.equal(step19(0), 19);
  assert.equal(step20(0), 20);
  assert.equal(step21(0), 21);
  assert.equal(step22(0), 22);
  assert.equal(step23(0), 23);
  assert.equal(step24(0), 24);
  assert.equal(step25(0), 25);
});
